<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Aktuelles und Wissenswertes</name>
   <tag></tag>
   <elementGuidId>89d7e2de-f752-4139-b387-db63b9317230</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;module-6&quot;]/div/nav/ul/li[9]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;module-6&quot;)/div[@class=&quot;masthead__inner&quot;]/nav[@class=&quot;masthead__navbar&quot;]/ul[@class=&quot;masthead__navbar-items&quot;]/li[@class=&quot;masthead__navbar-item masthead__navbar-item--active&quot;]/a[@class=&quot;masthead__navbar-link&quot;][count(. | //*[@id = 'module-6']) = count(//*[@id = 'module-6'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/de-ch/qualified-investor/news-and-insights</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masthead__navbar-link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aktuelles und Wissenswertes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;module-6&quot;)/div[@class=&quot;masthead__inner&quot;]/nav[@class=&quot;masthead__navbar&quot;]/ul[@class=&quot;masthead__navbar-items&quot;]/li[@class=&quot;masthead__navbar-item masthead__navbar-item--active&quot;]/a[@class=&quot;masthead__navbar-link&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>module-6</value>
   </webElementProperties>
</WebElementEntity>
