<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Franais</name>
   <tag></tag>
   <elementGuidId>d9c03338-47d4-4b0a-8e71-b41d5ce11583</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;countrySwitcher&quot;]/div/div/div[2]/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[count(. | //*[@href = '/fr-ch/qualified-investor']) = count(//*[@href = '/fr-ch/qualified-investor'])][count(. | //*[text() = 'Français']) = count(//*[text() = 'Français'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-language</name>
      <type>Main</type>
      <value>Français</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/fr-ch/qualified-investor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Français</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;countrySwitcher&quot;)/div[@class=&quot;country-switcher__dropdown&quot;]/div[@class=&quot;country-switcher__dropdown_inner&quot;]/div[@class=&quot;country-switcher__language-bar&quot;]/ul[@class=&quot;country-switcher__language-bar-options&quot;]/li[@class=&quot;country-switcher__language-bar-option&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
