<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Unser Ansatz</name>
   <tag></tag>
   <elementGuidId>0db3e397-2460-472d-a3ab-06074d54281b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navtray__tray-link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/de-ch/qualified-investor/about-us/our-approach</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unser Ansatz</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Über-uns&quot;)/div[@class=&quot;navtray__tray-inner&quot;]/div[@class=&quot;navtray__tray-items-wrapper&quot;]/ul[@class=&quot;navtray__tray-items&quot;]/li[@class=&quot;navtray__tray-item&quot;]/a[@class=&quot;navtray__tray-link&quot;]</value>
   </webElementProperties>
</WebElementEntity>
