<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_hero-promo__inner (1)</name>
   <tag></tag>
   <elementGuidId>c35c2d23-8b27-49a1-9af1-e3356011be34</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hero-promo__inner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;herob62e7678b6f34f47a1e6bfac1e597807&quot;)/div[@class=&quot;hero__inner&quot;]/div[@class=&quot;hero__main-container&quot;]/div[@class=&quot;hero__main-container-inner&quot;]/div[@class=&quot;hero__upper-component&quot;]/div[@class=&quot;hero-promo&quot;]/div[@class=&quot;hero-promo__inner&quot;]</value>
   </webElementProperties>
</WebElementEntity>
