<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_investor-type-selector__it</name>
   <tag></tag>
   <elementGuidId>9b48fd38-4887-413a-a1de-5a5e23a35151</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>investor-type-selector__item-inner-content</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;module-11&quot;)/div[@class=&quot;investor-type-selector__item&quot;]/div[@class=&quot;investor-type-selector__item-inner&quot;]/div[@class=&quot;investor-type-selector__item-inner-content&quot;]</value>
   </webElementProperties>
</WebElementEntity>
