<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon_Deutsch</name>
   <tag></tag>
   <elementGuidId>8550bed6-33aa-4df6-96ed-6c2fed8a66f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>id(&quot;countrySwitcher&quot;)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//i[count(. | id(&quot;countrySwitcher&quot;)/a[@class=&quot;country-switcher__current&quot;]/i[@class=&quot;icon&quot;]) = count(id(&quot;countrySwitcher&quot;)/a[@class=&quot;country-switcher__current&quot;]/i[@class=&quot;icon&quot;])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;countrySwitcher&quot;)/a[@class=&quot;country-switcher__current&quot;]/i[@class=&quot;icon&quot;]</value>
   </webElementProperties>
</WebElementEntity>
