<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon (1)</name>
   <tag></tag>
   <elementGuidId>12cd7741-69d3-44c8-bd67-4dd852abff4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>id(&quot;countrySwitcher&quot;)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//i[count(. | //*[@class = 'icon']) = count(//*[@class = 'icon'])][count(. | //*[@aria-hidden = 'true']) = count(//*[@aria-hidden = 'true'])][count(. | id(&quot;countrySwitcher&quot;)/a[@class=&quot;country-switcher__current&quot;]/i[@class=&quot;icon&quot;]) = count(id(&quot;countrySwitcher&quot;)/a[@class=&quot;country-switcher__current&quot;]/i[@class=&quot;icon&quot;])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;countrySwitcher&quot;)/a[@class=&quot;country-switcher__current&quot;]/i[@class=&quot;icon&quot;]</value>
   </webElementProperties>
</WebElementEntity>
