<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p</name>
   <tag></tag>
   <elementGuidId>19d3eb08-8128-4b61-ba3d-178dce622aed</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terms-and-conditions-modal&quot;)/div[@class=&quot;modal__body&quot;]/div[@class=&quot;terms-and-conditions-modal&quot;]/div[@class=&quot;terms-and-conditions-modal__body&quot;]/p[7]</value>
   </webElementProperties>
</WebElementEntity>
