<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GB country flag</name>
   <tag></tag>
   <elementGuidId>a2608cce-63ae-40d1-a43e-281704c6e321</elementGuidId>
   <imagePath>C:\Users\ghetherington\Desktop\GB_country_flag.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;countrySwitcher&quot;]/a/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//img[@src = '/-/media/amg/components/navigation/countryswitcher/countryflags/gb.svg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>country-switcher__flag</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/-/media/amg/components/navigation/countryswitcher/countryflags/gb.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;countrySwitcher&quot;)/a[@class=&quot;country-switcher__current&quot;]/img[@class=&quot;country-switcher__flag&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>img</name>
      <type>Main</type>
      <value>gb.svg</value>
   </webElementProperties>
</WebElementEntity>
